---
title: "Appendix"
author: "Yuki Wang"
date: "12/11/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("httr")
library("rjson")
search <- 'covid'
first_Result <- 0
number_OfResults <- 20
headers <- c(
  "Content-Type" = "application/x-www-form-urlencoded; charset=UTF-8",
  "Accept" = "application/json, text/javascript, */*; q=0.01",
  "Accept-Language" = "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
  "Accept-Encoding" = "gzip, deflate",
  "User-Agent" = "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)"
)
url<-"https://www.imf.org/coveo/rest/v2?sitecoreItemUri=sitecore%3A%2F%2Fweb%2F%7B5ABCDAEC-30A6-4F1B-835C-5D1AB8F77FB5%7D%3Flang%3Den%26amp%3Bver%3D1&siteName=imf"
body <- list(q=search,firstResult=first_Result,numberOfResults=number_OfResults,searchHub='SearchNews'
             ,aq='(((((((((((@imftype=="News Article" OR @imftype=="Press Release") OR @imftype==Communique) OR @imftype=="Mission Concluding Statement") OR @imftype=="News Brief") OR @imftype=="Public Information Notice") OR @imftype==Speech) OR @imftype=="Statements at Donor Meeting") OR @imftype==Transcript) OR @imftype=="Views and Commentaries") NOT @z95xtemplate==(ADB6CA4F03EF4F47B9AC9CE2BA53FF97,FE5DD82648C6436DB87A7C4210C7413B))) (@source=="Coveo_web_index - PRD93-SITECORE-IMFORG") (@imfdate)'
             ,cq='(@z95xlanguage==en) (@z95xlatestversion==1)'
             ,sortCriteria='@imfdate descending'
             )
r <- POST(url,body = body, encode = "form", verbose(),add_headers(.headers = headers))
result <- content(r, "parsed")
url_list <- list()
for(n in 1:number_OfResults){
  print(result[["results"]][[n]][["clickUri"]])
  url_list <- c(url_list,result[["results"]][[n]][["clickUri"]])
  print("-------------------------------")
}

```

